# This job is to test different maven profiles in sdk branch again Pull Request raised
# This workflow targets Java with Maven execution

name: TestNG SDK Test workflow for Maven on comment RUN_TESTS

on:
  - push
  - issue_comment:
      branches: [ "test-gh-workflow" ]
      types: [ created ]

jobs:
  comment-run:
    if: contains(github.event.comment.body, 'RUN_TESTS') && github.event.issue.pull_request
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        java: [ '8', '11', '17' ]
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
    name: TestNG Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: check-membership
        with:
          script: |
            const creator = context.payload.sender.login
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: 'asi-devs',
              username: creator
            })
            console.log(`The comment creator ${creator} membership - ${result}`)
            if (response.state === "active") {
                return "true"
            }
            core.setFailed('User is not part of the owner team!')
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
      - name: Run mvn profile sample-local-test
        run: |
          mvn compile
          mvn test -P sample-local-test
      - name: Run mvn profile sample-test
        run: |
          mvn compile
          mvn test -P sample-test
